CREATE TABLE IF NOT EXISTS ECON_AGENT_DB.ANALYTICS.APP_DAILY_QUOTA (
    QUOTA_KEY VARCHAR NOT NULL,
    UTC_DATE DATE NOT NULL,
    REQUEST_COUNT NUMBER(5, 0) NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL
);

MERGE INTO ECON_AGENT_DB.ANALYTICS.APP_DAILY_QUOTA AS target
USING (
    SELECT
        'PUBLIC_CHAT' AS QUOTA_KEY,
        TO_DATE(CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())) AS UTC_DATE
) AS source
ON target.QUOTA_KEY = source.QUOTA_KEY
WHEN NOT MATCHED THEN INSERT (QUOTA_KEY, UTC_DATE, REQUEST_COUNT, UPDATED_AT)
VALUES (source.QUOTA_KEY, source.UTC_DATE, 0, CURRENT_TIMESTAMP());

-- Run with the owning role. These least-privilege grants are idempotent.
GRANT SELECT, UPDATE ON TABLE ECON_AGENT_DB.ANALYTICS.APP_DAILY_QUOTA
    TO ROLE US_ECONOMY_APP_ROLE;
GRANT SELECT ON DYNAMIC TABLE ECON_AGENT_DB.ANALYTICS.ECONOMIC_DASHBOARD_LIVE TO ROLE US_ECONOMY_APP_ROLE;
